baseURL = 'https://chuxin3310.github.io'
title = 'PK'

languageCode = "zh-tw"
theme = "PaperMod"
buildDrafts = false 
[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10





title: "mySecondPost"
date: date
draft: false
tags: ["code","test"]
categories: ["Markdown"]

[params.profileMode]
enabled = true
title = "URIDIOT"
subtitle = "UR"
imageUrl = ""
imageHeight = 120
imageTitle = "ur"

	
[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"
 
[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"
