baseURL = 'https://chuxin3310.github.io'
title = 'PK'

languageCode = "zh-tw"
theme = "PaperMod"
buildDrafts = false 

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20



[params.profileMode]
enabled = true
title = "URIDIOT"
subtitle = "UR"
imageUrl = ""
imageHeight = 120
imageTitle = "ur"

	
[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"
 
[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"
