baseURL = 'https://chuxin3310.github.io'
title = 'chuxinsblog'

languageCode = "zh-tw"
theme = "PaperMod"
buildDrafts = false 

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
 identifier = "archives" 
 name = "Archives"
 url = "/archives/"
 weight = 30

[params.profileMode]
enabled = true
title = "chuxin"
subtitle = "chunithm、Phigros..."
imageUrl = "img/ouo.jpg"
imageWidth =120 # custom size
imageHeight = 120 # custom size
imageHeight = 100
imageTitle = "waifu"
	
[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "github"
url = "https://chuxin3310.github.io"
#...more

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視
