baseURL = 'https://chuxin3310.github.io'
title = 'chuxinsblog'

languageCode = "zh-tw"
theme = "PaperMod"
buildDrafts = false 

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10


[[menu.main]]
 identifier = "archives" 
 name = "Archives"
 url = "/archives/"
 weight = 30

 [[menu.main]]
name = "ZJ"
url = "/zerojudge/"
weight = 40

[params.profileMode]
enabled = true
title = "chuxin"
subtitle = "c++、zerojudge..."
imageUrl = "img/ouo.jpg"
imageWidth =120 # custom size
imageHeight = 120 # custom size
imageTitle = "waifu"
	
[[params.profileMode.buttons]]
name = "Blog"
url = "/zerojudge/"

[[params.profileMode.buttons]]
name = "zerojudge"
url = "/zerojudge/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/chuxin3310"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/profile.php?id=100068352667542"

[[params.socialIcons]]
name = "youtube"
url = "https://youtube.com/@Cx_chuxin"

[params] 
ShowBreadCrumbs = true    
#展示文章所在目錄
ShowReadingTime = true    
#展示閱讀時間
ShowShareButtons = true    
#展示分享按鈕
ShowPostNavLinks = true    
#本地其他文章連結

[params.cover]
linkFullImages = true    
#點擊圖片後以全螢幕檢視
