title = 'PK'
baseurl = "https://chuxin3310.github.io"
languageCode = "zh-tw"
theme = "PaperMod"
buildDrafts = false 
[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10

[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30

title: "mySecondPost"
date: date
draft: false
tags: ["code","test"]
categories: ["Markdown"]

[params.profileMode]
enabled = true
title = "URIDIOT"
subtitle = "UR"
imageUrl = "
imageHeight = 120
imageTitle = "ur"
