baseURL = 'https://chuxin3310.github.io'
title = 'chuxin_s_blog'
theme = "terminal"
languageCode = "zh-tw"

# Pagination
paginate = 5

[params]
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # dir name of your main content (default is "posts")
  contentTypeName = "posts"

  # show "Read more" button in the list
  showReadMore = true

  # show "Reading time" in the post header
  showReadingTime = true

  # custom subtitle for the home page
  subtitle = "> chuxin --version v2.0"

  # custom footer text
  [params.footer]
    copyright = "© 2026 chuxin"
    poweredBy = true

[menu]
  # Main menu items
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "zerojudge"
    name = "ZeroJudge"
    url = "/zerojudge/"
    weight = 20

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives"
    weight = 30
