title = 'PK'
baseurl = "https://chubof.github.io
languageCode = "zh-tw"
theme = "PaperMod"
buildDrafts = false 
[[menu.main]]

identifier = "tags"

name = "tags"

url = "/tags/"

weight = 10

[[menu.main]]

identifier = "categories"

name = "Categories"

url = "/categories/"

weight = 20

[[menu.main]]

identifier = "archives"

name = "Archives"

url = "/archives/"

weight = 30
